services:
    clojure:
        build:
            context: ..
            dockerfile: ./docker/clojure/Dockerfile
        volumes:
            - ../src/:/usr/src/clojure-in-docker/src/
            - ../test/:/usr/src/clojure-in-docker/test/
        stdin_open: true
        tty: true
        networks:
            - backend
        ports:
            - "7888:7888"
        entrypoint:
            ["lein", "repl", ":headless", ":host", "0.0.0.0", ":port", "7888"]

networks:
  backend:
    driver: "bridge"
